server:
  port: 8091

spring:
  application:
    name: products
  data:
    mongodb:
      uri: "mongodb+srv://admin:123@cluster0.ppfqx.mongodb.net/test"
    rest:
      basePath: "/"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
